nelmio_cors:
  defaults:
    origin_regex: true
    #allow_origin: ['http://localhost:4200']
    allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    expose_headers: ['Link', 'X-Total-Count']
    max_age: 3600
    allow_credentials: false
  paths:
    '^/api/': ~

# nelmio_cors:
#     defaults:
#         origin_regex: true
#         # allow_origin: ['http://localhost:4200']
#         allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE','OPTIONS']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:      
#         '^/api/':  # Applique la configuration CORS à toutes les routes API
#             allow_origin: ['http://localhost:4200']
#             allow_headers: ['content-type', 'authorization']
#             expose_headers: ['link']
#             allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE','OPTIONS']
#             max_age: 3600

# nelmio_cors.yaml

# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization', 'Preload', 'Fields']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:
#         '^/': null
# nelmio_cors:
#   defaults:
#     origin_regex: true
#     allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#     allow_headers: ['content-type', 'authorization', 'Accept']
#     allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
#     max_age: 3600
#   paths:
#     '^/api/': ~

# nelmio_cors:
#   defaults:
#     allow_origin: []
#     allow_credentials: false
#     allow_headers: ["Content-Type", "Authorization", "Accept"]
#     allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
#     expose_headers: []
#     max_age: 3600
#   paths:
#     "^/api/":
#       allow_origin: ["*"]
#       allow_headers: ["Content-Type", "Authorization", "Accept"]
#       allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
#       max_age: 3600
