# nelmio_cors:
#     defaults:
#         allow_credentials: false
#         allow_origin: ['http://localhost:4200']  # Origine autorisée
#         allow_headers: ['content-type', 'authorization']
#         expose_headers: ['link']
#         allow_methods: ['GET', OPTIONS', 'POST', 'PUT', 'DELETE']
#         max_age: 3600
    # paths:
    #     '^/api/':  # Applique la configuration CORS à toutes les routes API
    #         allow_origin: ['http://localhost:4200']
    #         allow_headers: ['content-type', 'authorization']
    #         expose_headers: ['link']
    #         allow_methods: ['GET', OPTIONS', 'POST', 'PUT', 'DELETE']
    #         max_age: 3600

     