services:
  db:
    image: mysql
    container_name: db_sf-api-pressing
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_sf-api-pressing
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build: docker
    container_name: www_sf-api-pressing
    ports:
      - "9000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
# services:
#   php:
#     image: php:8.3-apache
#     container_name: php83-apache
#     ports:
#       - "9000:80"
#     volumes:
#       #- ./php:/var/www/html
#       - ./php:/var/www/html
#     build:
#       context: .
#       dockerfile: Dockerfile

#     depends_on:
#       - db_mysql # nom du service de la database

#   db_mysql:
#     image: mysql:8.0
#     container_name: mysql8

#     environment:
#       MYSQL_ROOT_PASSWORD: pass
#       # MYSQL_ROOT_PASSWORD: pass
#       # MYSQL_DATABASE: sf-api-pressing
#       # MYSQL_USER: root
#       # MYSQL_PASSWORD: pass
#     volumes:
#       - ./mysql_data:/var/lib/mysql
#     ports:
#       - "3307:3306"

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     container_name: phpmyadmin
#     depends_on:
#       - db_mysql # nom du service de la database
#     environment:
#       PMA_HOST: mysql8 # nom du container de la database
#       MYSQL_ROOT_PASSWORD: pass
#     ports:
#       - "9081:80"
# volumes:
#   mysql_data:
# services:
#   ###> doctrine/doctrine-bundle ###
#   database:
#     image: postgres:${POSTGRES_VERSION:-16}-alpine
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB:-app}
#       # You should definitely change the password in production
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#       POSTGRES_USER: ${POSTGRES_USER:-app}
#     volumes:
#       - database_data:/var/lib/postgresql/data:rw
#       # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#       # - ./docker/db/data:/var/lib/postgresql/data:rw
# ###< doctrine/doctrine-bundle ###

# volumes:
#   ###> doctrine/doctrine-bundle ###
#   database_data:
# ###< doctrine/doctrine-bundle ###
